### PR TITLE
Fix Issue 1180 - the GC failes to handle large allocation requests propperly 

### PR DESCRIPTION
**Pull request by rainers**
report out-of-memory for allocation a bit below size_t.max

even though reported as a regression, this doesn't seem like anything new, so it might not be necessary to merge into stable.

### CODE REVIEW

**Comment by DmitryOlshansky** [comment]
LGTM

**Comment by DmitryOlshansky** [comment]
Auto-merge toggled on

**Comment by schveiguy** [comment]
Auto-merge toggled off

**Comment by schveiguy** [comment]
Re-enable auto merge after fix for win64 build

**Comment by schveiguy** [comment]
Auto-merge toggled on

**Pull request merged**
