### PR TITLE
Fix Issue 15104 - Fiber context switch in finally blocks breaks EH

### PR DESCRIPTION
**Pull request by klickverbot**
https://issues.dlang.org/show_bug.cgi?id=15104

### CODE REVIEW

**Comment by ibuclaw** [comment]
:+1: - Fix works for gdc too.

**Comment by MartinNowak** [comment]
Can we store it as Fiber field and on the stack instead? I want to get rid of the Context within chain at some point.

**Comment by MartinNowak** [comment]
I want to keep the array of Contexts with stacktop/bottom for the GC, the nested push/pop Context is only needed to find out whether the stack pointer during a GC suspend is in the thread's stack or the current Fiber's stack. This can be done by checking the stack range instead.
But anyhow, keeping this variable on the stack is simple enough.

**Comment by MartinNowak** [comment]
I think you can because the context switching itself does not throw.

**Pull request merged**
