### PR TITLE
fix Issue 14350 - Unit test failures are not displayed in Windows GUI pr...

### PR DESCRIPTION
**Pull request by CyberShadow**
...ograms

https://issues.dlang.org/show_bug.cgi?id=14350

### CODE REVIEW

**Comment by CyberShadow** [comment]
BTW, shouldn't Druntime `extern(C)` functions have a `_d_` prefix OSLT? We're polluting the C namespace.

**Comment by MartinNowak** [comment]
Yes, can you please change it to _d_print_throwable?

**Comment by CyberShadow** [comment]
Done, though this is one of many.

Also I hope this won't break code in case people are calling this function manually from their WinMain functions OSLT.

**Comment by MartinNowak** [comment]
Used to be `private void printThrowable(Throwable t)` (even `extern(D)`), pretty hard to call that one.

**Comment by MartinNowak** [comment]
Auto-merge toggled on

**Comment by CyberShadow** [comment]
Oh, doh. Right.

**Pull request merged**
