### PR TITLE
fixes for reading EH info

### PR DESCRIPTION
**Pull request by WalterBright**
Required for https://github.com/D-Programming-Language/dmd/pull/5469

### CODE REVIEW

**Comment by MartinNowak** [comment]
Some reference would be nice (also in the commit message), it reduces maintenance overhead not having to search the whole internet to figure out why those constants where used.

**Comment by MartinNowak** [comment]
Auto-merge toggled on

**Comment by WalterBright** [comment]
Those constants are used in the EH table format documentation, such as it is. Interestingly, googling on the constant name will take you pretty much right to it.

**Comment by MartinNowak** [comment]
Must be your own search bubble, but on page 4 I found this nice overview article http://www.airs.com/blog/archives/460.

**Pull request merged**
