### PR TITLE
add high-level Library wrapper …

### PR DESCRIPTION
**Pull request by MartinNowak**
- loadLib now returns a Library struct
- Library sub-types the native platform handle (alias this)
- Library.findFunc loads a D mangled function
- Library.findVar loads a D mangled variable

The single most annoying pull request I ever prepared. Too many long-standing unrelated bugs for such a straightforward implementation.

### CODE REVIEW

**Comment by andralex** [comment]
@MartinNowak this seemed to go on the backburner... close until you can get back to it?

**Comment by transfuturist** [comment]
@MartinNowak Is this branch still viable? This feature is pretty valuable.

**Comment by MartinNowak** [comment]
> @MartinNowak Is this branch still viable? This feature is pretty valuable.

Yes, but I'm busy with other topics currently.

**Comment by Domain** [comment]
@MartinNowak 4 years passed! Any plan to update this?

**Pull request closed without merging**
