### PR TITLE
setAssertHandler is deprecated

### PR DESCRIPTION
**Pull request by WalterBright**

### CODE REVIEW

**Comment by andralex** [comment]
Auto-merge toggled on

**Comment by yebblies** [comment]
From the comment earlier in the function: `// Bring in unit test for module by referencing a function in it`

Shouldn't the call be replaced with another from the same module, instead of deleted?

**Comment by rainers** [comment]
> Shouldn't the call be replaced with another from the same module, instead of deleted?

unittest.d is obsolete because all the source files are passed on the command line anyway, passing `-main` on the command line should be enough. The linux test_runner.d also doesn't have any 'drag in' code.

**Comment by yebblies** [comment]
So... unittest.d should be deleted?

**Comment by rainers** [comment]
I just tried `-main` instead of unittest.d and printed called tests in `runModuleUnitTests`: seems to work fine. I'm fine with deleting unittest.d.

**Comment by yebblies** [comment]
Like this? https://github.com/D-Programming-Language/druntime/pull/1125

**Comment by rainers** [comment]
> Like this? #1125

Yes. I just tried the same with phobos: there are some minor tests in unittest.d there, but there are also instantiations of templates with unittests that then run as part of unittest.d. I'm not sure if this is deliberate.

**Pull request merged**
