### PR TITLE
fix Issue 14573 - classes without destructor leak monitor/mutex

### PR DESCRIPTION
**Pull request by MartinNowak**
- set finalize bit when constructing the monitor
- fix race condition (incorrect double checked locking)
- optimistically init mutex before locking global mutex
  to reduce contention
- remove pointless code duplication of Windows/Posix implementation
- move implementation details into private D functions
- use shared(Monitor)* whenever dealing with an unsynchronized instance
  and Monitor* when it's already externally synchronized
- modernize code for better readability
- drop using STI/STD style C constructors (called by rt_init/rt_term)

[Issue 14573 – [REG2.067] Extreme memory usage when `synchronized( object )` is used](https://issues.dlang.org/show_bug.cgi?id=14573)

### CODE REVIEW

**Comment by schveiguy** [comment]
Seems like a good idea, I like it. LGTM, though I'd like to avoid the double-set of the flag if the monitor happens to be set when calling the function.

**Comment by schveiguy** [comment]
Are those the only lines with CRLF? seems weird...

**Comment by MartinNowak** [comment]
Sorry for the huge rewrite, but there was too much wrong with this module.

**Comment by MartinNowak** [comment]
Let's just merge both in #1274.

**Pull request closed without merging**
