### PR TITLE
don't reset memory of finalized classes/structs/arrays

### PR DESCRIPTION
**Pull request by MartinNowak**

### CODE REVIEW

**Comment by andralex** [comment]
Risky but efficient.

**Comment by MartinNowak** [comment]
> Risky but efficient.

Rather not, because it was freed by the GC. And when the men is allocated again you hopefully don't forget to initialize it ;).
We already did it for classes, so this just applies existing behavior to structs and writing to all the reclaimed memory is extremely expensive.

**Comment by schveiguy** [comment]
`finalize_array2` is called by GC, `finalize_array` I believe is still called by doing `delete arr` (haven't verified this)

That being said, I still think this change is fine.

**Comment by MartinNowak** [comment]
But delete ary wasn't resetting memory before #864.

**Comment by schveiguy** [comment]
Sure, and really, `delete` frees the memory, so any access to a dangling reference is invalid whether you re-initialize or not.

**Pull request merged**
