### PR TITLE
Remove unittest.d

### PR DESCRIPTION
**Pull request by yebblies**

### CODE REVIEW

**Comment by rainers** [comment]
LGTM, but let's give others some time to object. Function called from unittest.d, but not covered by unittests might get less coverage.

**Comment by rainers** [comment]
The build command line now needs to use `-of`.

**Comment by yebblies** [comment]
Updated

**Comment by andralex** [comment]
Does this change anything in posix.mak?

**Comment by yebblies** [comment]
posix.mak doesn't appear to use unittest.d at all.

**Pull request merged**
