### PR TITLE
Removed deprecated clear method

### PR DESCRIPTION
**Pull request by JinShil**
Context:
https://github.com/D-Programming-Language/druntime/pull/757
http://forum.dlang.org/post/wcoscawhmagambkydrye@forum.dlang.org
https://github.com/D-Programming-Language/druntime/pull/999

### CODE REVIEW

**Comment by yebblies** [comment]
Looks like it's been deprecated for >6 months, time to kill it.

**Comment by yebblies** [comment]
Auto-merge toggled on

**Comment by schveiguy** [comment]
I'm working on a PR to fix the phobos message

**Comment by schveiguy** [comment]
Please see referenced PR, once that's pulled, this should compile.

**Comment by yebblies** [comment]
Auto-merge toggled off

**Comment by schveiguy** [comment]
There's some kind of an issue with the auto tester, it should have deprecated all its tests when the other PR was merged. I'm not sure what's going on, but I emailed Brad.

**Comment by MartinNowak** [comment]
Maybe the github hook delivery got lost.

**Comment by schveiguy** [comment]
Well, I manually deprecated all the tests, so if we merge this, maybe it will reset.

**Comment by schveiguy** [comment]
@yebblies why did you switch of the auto merge? Is there an objection somewhere?

**Comment by yebblies** [comment]
Auto-merge toggled on

**Comment by yebblies** [comment]
No, I switched it off because it was failing.

**Pull request merged**
