### PR TITLE
Windows:unhandled exception dump should not show dialog if stderr is redirected

### PR DESCRIPTION
**Pull request by rainers**
Followup for #703

### CODE REVIEW

**Comment by CyberShadow** [comment]
Will it ever be `INVALID_HANDLE_VALUE`? IIRC std.process has to check for both `null` and `INVALID_HANDLE_VALUE`: https://github.com/D-Programming-Language/phobos/pull/3148

**Comment by CyberShadow** [comment]
This is an improvement but I think ideally it should display the message box if it tries and fails to write to stderr (e.g. if it points to a closed file). If stderr is reopened by the application, this might not do what the user expects.

**Comment by rainers** [comment]
> Will it ever be INVALID_HANDLE_VALUE?

I used null because of this note in the MSDN doc for GetStdHandle: "If an application does not have associated standard handles, such as a service running on an interactive desktop, and has not redirected them, the return value is NULL."

Checking for INVALID_HANDLE_VALUE would probbly be ok, too.

**Comment by rainers** [comment]
> ideally it should display the message box if it tries and fails to write to stderr

In that case fprintf should return 0, but it's a bit ugly to check because it is only called in the sink delegate. Can we add printing some header?

**Comment by CyberShadow** [comment]
How about prefixing "Unhandled "? Or would that break editors/IDEs matching the error string?

**Comment by rainers** [comment]
I changed it to try writing a newline, so the exception is also guaranteed to be shown at the beginning of a line.

**Comment by DmitryOlshansky** [comment]
LGTM

**Comment by DmitryOlshansky** [comment]
@CyberShadow all good on this one?

**Comment by CyberShadow** [comment]
Yep. Getting used to a newline before stack traces will be a tiny nuisance, but it's justified.

**Comment by DmitryOlshansky** [comment]
Auto-merge toggled on

**Pull request merged**
