### PR TITLE
Make TickDuration "to" a freestanding, non-member function

### PR DESCRIPTION
**Pull request by mrkline**
This gives it the same semantics as all "normal" `to` functions in std.conv, allowing you to call it as `to!Duration(tickDur)` or in the current manner via UFCS. Fewer edge cases is good.

This also seems to fix conversions from `TickDuration` to `Duration`. At time of writing, the following fails to compile with the druntime master branch but compiles with this branch:

```d
import std.stdio;
import std.conv : to;
import std.datetime : Clock, Duration;

void main()
{
	write("System has been up for ");
	writeln(Clock.currSystemTick.to!Duration.total!"seconds", " seconds.");
}

```

### CODE REVIEW

**Comment by MartinNowak** [comment]
TickDuration is about to be replaced by MonoTime.

**Comment by MartinNowak** [comment]
Auto-merge toggled on

**Comment by MartinNowak** [comment]
There are complaints about overload issues, see the reference above.

**Comment by mrkline** [comment]
Hm. Perhaps I'm misunderstanding template rules, but how could this overshadow `to!string` when it takes a different number of template arguments and seems to have constraints that would preclude `string` from being the first template argument?

**Comment by burner** [comment]
there is also a stray "this" inside

**Comment by CyberShadow** [comment]
This pull request introduced a regression:
https://issues.dlang.org/show_bug.cgi?id=14530

**Comment by 9rnsr** [comment]
This pull request introduced a regression:
https://issues.dlang.org/show_bug.cgi?id=15179

**Pull request merged**
