### PR TITLE
[Trivial] Fix typo in unittest

### PR DESCRIPTION
**Pull request by MetaLang**

### CODE REVIEW

**Comment by CyberShadow** [comment]
There's another one on line 1735.

**Comment by quickfur** [comment]
LGTM.

**Comment by MetaLang** [comment]
Unfortunately I cannot currently squash the second commit, so we can just wait for a bit before merging.

**Comment by MetaLang** [comment]
Squashed and ready to merge.

**Comment by ZombineDev** [comment]
LGTM

**Comment by CyberShadow** [comment]
Auto-merge toggled on

**Pull request merged**
