### PR TITLE
[Refactor] Don't use loop in `rt.aaA.nextpow2`.

### PR DESCRIPTION
**Pull request by denis-sh**
Also add unittest.

### CODE REVIEW

**Comment by denis-sh** [comment]
@MartinNowak, is `nextpow2` really supposed to work with zero or should it reject such case?

**Comment by schveiguy** [comment]
Auto-merge toggled on

**Comment by schveiguy** [comment]
I think for the time it takes to check for zero, it's not worth allowing potentially undefined behavior

**Comment by MartinNowak** [comment]
Thanks.
This is not performance relevant anyhow.

**Pull request merged**
