### PR TITLE
fix Issue 14104 - aa with pointer key type doesn't find existing value

### PR DESCRIPTION
**Pull request by MartinNowak**
- the internal TypeInfo_P.getHash for pointers trucated the hash to
  32-bit unlike the TypeInfo_Pointer.getHash
- internal TypeInfos are used when no full type information is needed
  so they must behave identical

[Issue 14104 – aa with pointer key type doesn't find existing value](https://issues.dlang.org/show_bug.cgi?id=14104)

### CODE REVIEW

**Comment by rainers** [comment]
Although this fixes the issue, wouldn't it be more correct to supply the proper type info? I.e. ban getInternalTypeInfo from the compiler.

**Comment by Safety0ff** [comment]
```TypeInfo_P.compare``` looks buggy too, I think it should be brought in line with ```TypeInfo_Pointer.compare```.
(I also wonder the same thing as rainers.)

**Comment by MartinNowak** [comment]
> Although this fixes the issue, wouldn't it be more correct to supply the proper type info? I.e. ban getInternalTypeInfo from the compiler.

That's a different topic and as [the comment](https://github.com/D-Programming-Language/dmd/blob/3dcdb1608b35595926c3c133687c79a5f1bf3ad1/src/typinf.c#L44) says, it makes sense to use as few TypeInfo objects as possible.

**Comment by MartinNowak** [comment]
fixed

**Comment by Safety0ff** [comment]
LGTM.

**Comment by rainers** [comment]
> That's a different topic and as the comment says, it makes sense to use as few TypeInfo objects as possible.

The comment seems out of date, too. For example, static arrays are no longer translated to dynamic arrays. I think getInternalTypeInfo is a bad case of premature optimization. It's only used for some AA operations, array comparisons and array.sort (though explicitely not called for static arrays there).

**Comment by MartinNowak** [comment]
Well, go ahead and remove it if the footprint is neglectable. You've worked a lot more with TypeInfo than I did.

**Pull request merged**
