### PR TITLE
shared library support for FreeBSD

### PR DESCRIPTION
**Pull request by MartinNowak**
- use handle instead of linkmap to identify DSOs

- merge rt.sections_freebsd and rt.sections_linux into rt.sections_elf_shared

- handle the few OS specific differences

### CODE REVIEW

**Comment by MartinNowak** [comment]
works now

**Comment by joakim-noah** [comment]
Hope this gets in soon.  `rt.sections_elf_shared` would benefit from some documentation comments about the DSO registry scheme you're using, particularly now that it's being used on multiple ELF platforms.  Other than that and not really following all the shared library code because I'm not familiar with all the technical details, LGTM, as it passes the tests on FreeBSD.

**Comment by MartinNowak** [comment]
> DSO registry scheme you're using

Well, the each DSO calls into druntime and registers it's metadata sort of scheme.

**Comment by joakim-noah** [comment]
>the each DSO calls into druntime and registers it's metadata sort of scheme

Right, it would help others if you expand that description out into more detail, [in an overview comment like this](https://github.com/D-Programming-Language/druntime/blob/master/src/rt/sections_osx.d#L105).  That OS X TLS scheme is much simpler than what you're doing, yet it does a better job of actually describing what the overall scheme is doing.  Your code has some good comments in various places, but would benefit from a better overall description.

**Comment by MartinNowak** [comment]
Passes since a week!

**Comment by MartinNowak** [comment]
ping

**Comment by MartinNowak** [comment]
Starts to bitrot, can we please merge this?
There are enough tests to cover these changes.

**Comment by MartinNowak** [comment]
Auto-merge toggled on

**Pull request merged**
