### PR TITLE
No more GC.free when removing entry from associative array

### PR DESCRIPTION
**Pull request by andralex**
We've had a really nasty heisenbug in production caused by code like this:

```d
bool[int] aa;
...
if (auto p = (k in aa))
{
    aa.remove(k);
    if (*p) ...
}
```

Built-in associative arrays must be safe. cc @MartinNowak

### CODE REVIEW

**Comment by WalterBright** [comment]
Auto-merge toggled on

**Comment by MartinNowak** [comment]
The symptom is real, but the conclusion is wrong.
He's not holding the value but a pointer to the internal value that is just deleted afterwards.
It's similar to doing this with an array.
```d
auto p = &ary[$-1];
ary.length -= 1;
// p is now a dangling pointer
```
If you seriously wanted to make the above code correct then we can no longer store values in containers, only references (`new int`), so that the container can safely return a pointer to the value.
It's just a sign of how bad the current AA implementation is, that it actually does GC allocate each value, even integers, but it's a mistake to kill one of the most important hash table optimization.
Using the `in` operator for more than a bool check is an inherently unsafe operation (can return null btw), just like directly taking the address.

**Comment by MartinNowak** [comment]
[Issue 14103 – dmd doesn't treat opIn as unsafe](https://issues.dlang.org/show_bug.cgi?id=14103)

**Comment by andralex** [comment]
Use of the pointer after a key removal may be incorrect but should not be undefined. We're already paying for GC; the built-in structures should be safe.

```d
auto p = &ary[$-1];
ary.length -= 1;
// p is now a dangling pointer
```

Why is this unsafe? Is there some memory deallocation going on?

**Comment by MartinNowak** [comment]
> Why is this unsafe? Is there some memory deallocation going on?

Sure, the array might get reallocated.

> We're already paying for GC

But we shouldn't, any decent AA would store small values inline and most AA values are very small.
The semantics you want basically require to allocate each value separately on the heap (combined with the key). And people are abusing the AA as set `void[0][int]`.

Another important optimization is to bundle allocations and using a freelist.

**Comment by MartinNowak** [comment]
I just looked through rt.lifetime and indeed there is no freeing or shrinking, so the pointer into the array still references alive memory.
If in analogy to the array behavior this pull is only worried about the memory and not the actual values then I'm fine with these semantics for AAs.
The important part is reusing remove value slots for new values.

**Comment by schveiguy** [comment]
I also don't necessarily agree with this change. I think there *should* be a way to remove a key and free the memory as well. It's unfortunate that remove was not simply originally marked as unsafe.

At the very least, we should zero the memory before forgetting it. AA's are notorious false-pointer sources.

**Comment by MartinNowak** [comment]
> I also don't necessarily agree with this change. I think there should be a way to remove a key and free the memory as well. It's unfortunate that remove was not simply originally marked as unsafe.

Andrei is right about the memory, the GC will collect it eventually and we can't free it to avoid memory corruption bugs.

> At the very least, we should zero the memory before forgetting it. AA's are notorious false-pointer sources.

I'll likely rewrite the AA implementation in the next few days and will take care of that.

**Comment by schveiguy** [comment]
It's actually probably best for the GC to free it. However, I think there are some use cases that would devolve quickly. For example, if you are frequently removing and adding keys, but always keeping the size constant, the GC may consume much more memory than you want it to. By freeing the element, it puts it on the free list, and that will allow quick allocation for the next element. But I suppose that's a job for an allocator.

> At the very least, we should zero the memory before forgetting it.

I just realized, we likely only want to zero the key and pointer, not the value. Otherwise, using the value after the fact will fail. Unless we don't care about supporting that?

**Comment by MartinNowak** [comment]
> I just realized, we likely only want to zero the key and pointer, not the value. Otherwise, using the value after the fact will fail. Unless we don't care about supporting that?

No we don't, it's important that we don't corrupt memory.

**Comment by schveiguy** [comment]
> No we don't, it's important that we don't corrupt memory.

but on the other hand, if we simply forget the AA, then the memory will stay intact until unreferenced. Same deal if you take the address of a linear array element. I think if we are going to eliminate the `free` call, we should leave the data portion alone.

Note, no memory corruption should occur if we don't free the memory.

**Comment by MartinNowak** [comment]
Yep exactly,

**Comment by andralex** [comment]
@MartinNowak yah, exactly: that slot can be reused for a future insertion in the hashtable. That makes a program that keeps address of things after their deletion incorrect but not catastrophically unsafe. Thanks for the good points!

**Pull request merged**
