### PR TITLE
move _wsopen to core.sys.windows.io

### PR DESCRIPTION
**Pull request by MartinNowak**

### CODE REVIEW

**Comment by yebblies** [comment]
Why?

**Comment by MartinNowak** [comment]
Because it's in a separate `<io.h>` header and `core.sys.*.` is modeled after the corresponding C headers.

**Comment by jmdavis** [comment]
I don't really object to this except for the fact that we shove pretty much _everything_ in windows.d right now, and if we really want to fix that and rearrange the declarations properly, it makes more sense to rearrange them all rather than care particularly about this small subset of them, especially if creating extra files like this could actually make it harder to rearrange the Windows declarations correctly later when we actually do that (Adam Ruppe was talking about doing it the other day, so maybe we'll actually get some work done on that front soon - but i don't remember what he said his plan was exactly). But this is _probably_ where these declarations would go anyway, since it's where they are in the C headers.

**Comment by MartinNowak** [comment]
OK

**Pull request closed without merging**
