### PR TITLE
Fixes #15434: object.d must not import from rt

### PR DESCRIPTION
**Pull request by yazd**
https://issues.dlang.org/show_bug.cgi?id=15434

### CODE REVIEW

**Comment by yazd** [comment]
The auto-tester fails for some reason.. uhmm. I cannot reproduce on either a 32-bit or a 64-bit linux.

**Comment by schveiguy** [comment]
Seems it was a spurious failure, passed now.

**Comment by schveiguy** [comment]
I've not seen externDFunc before, interesting! Is that really the only way to declare an external d function? Almost all other runtime extern functions are hooked via C linkage. I'm not sure which way is better.

**Comment by yazd** [comment]
It is used several times in this file to link to `rt` functions.

**Comment by schveiguy** [comment]
OK, then I guess I just haven't read through it in a while :)
LGTM

**Comment by ZombineDev** [comment]
@yazd thanks for fixing this!

Btw I wonder how it worked in debug (no inline) mode.

@schveiguy this is a regression from DMD 2.067 (when the code used to work), so I hope this PR will be merged in time for the next release.

**Comment by yazd** [comment]
@ZombineDev :+1: 
I think it works with no inline because the compiler only uses the declaration and links directly to the compiled druntime (it doesn't recompile druntime). I might be wrong.

Is there anything else to address to get this pulled?
Thanks.

**Pull request merged**
