### PR TITLE
the writeThis value must not be const to support structs with pointers

### PR DESCRIPTION
**Pull request by MartinNowak**

### CODE REVIEW

**Comment by MartinNowak** [comment]
Ping

**Comment by rainers** [comment]
LGTM. "const" should be inferred for the template argument if necessary.

**Comment by rainers** [comment]
Auto-merge toggled on

**Comment by denis-sh** [comment]
Is compilation failure in case there is no "double-word" CAS intentional?

**Comment by MartinNowak** [comment]
> Is compilation failure in case there is no "double-word" CAS intentional?

What do you mean?

**Comment by denis-sh** [comment]
> What do you mean?

`hasDWCAS` is either `true` or undefined, it's never `false` so e.g. `static if (hasDWCAS) { x; }` works like `static assert(hasDWCAS); x;`

**Comment by rainers** [comment]
Ouch, if should have been `enum hasDWCAS = has128BitCAS;` and similar for 32-bit.

**Comment by rainers** [comment]
https://github.com/D-Programming-Language/druntime/pull/1170

**Comment by MartinNowak** [comment]
> hasDWCAS is either true or undefined, it's never false so e.g. static if (hasDWCAS) { x; } works like static assert(hasDWCAS); x;

This is what happens when you mix versions and static if ;).
Why didn't this trigger any test failure?

**Comment by denis-sh** [comment]
> Why didn't this trigger any test failure?

Looks like `D_InlineAsm_X86_64` or `D_InlineAsm_X86` are always defined.

**Pull request merged**
