### PR TITLE
fix FBSD shared library issues

### PR DESCRIPTION
**Pull request by MartinNowak**
- add tests for module collision check
- fix copy relocation check so it can deal with
  __bss_start/_end being defined in a DSO
- workaround FBSD bug ([Issue 14824](https://issues.dlang.org/show_bug.cgi?id=14824))
- reenable druntime-debug unittests

### CODE REVIEW

**Comment by jmdavis** [comment]
Well, I don't know if this was supposed to fix all of the shared library bugs that have been reported for FreeBSD or not, but these changes seem to fix https://issues.dlang.org/show_bug.cgi?id=14776. However, I'm still hitting https://issues.dlang.org/show_bug.cgi?id=14663 on my FreeBSD 10 system, and it looks like the tests are failing on several platforms on the autotester (including on Linux) - around the load_mod_collision test it looks like, which is after the link_linkdep test that is failing on my FreeBSD 10 system.

So, as far as the systems on the auto tester go, you seem to have fixed the issue with FreeBSD and debug builds while creating a new one, and the problem that was failing on FreeBSD 10 in release builds is still failing (and debug builds now hit the same failure instead of the one they were hitting before).

But _thank you_ for looking into this. I was afraid that I was going to have to start looking into the shared library issues, since I've been using FreeBSD of late, but I know nothing about how the shared library support works. And technically, FreeBSD 8.x will be at End-of-Life come August, so without shared library support getting fixed in FreeBSD 9 and/or 10, we soon won't actually be able to successfully run the druntime unit tests on a supported FreeBSD system (which of course doesn't say good things about how well it actually works on those systems). :(

**Comment by MartinNowak** [comment]
> around the load_mod_collision test it looks like,

The test itself works fine, but it seems that the tester doesn't like the pre-pipe command fail with a segfault (`assert(0)`).

**Comment by MartinNowak** [comment]
Found the linux issue. The distribution on the auto-tester uses `--as-needed` by default, and b/c it isn't used by link_mod_collision lib.so was not linked.

**Comment by MartinNowak** [comment]
Please don't let that bitrot, it's kinda difficult to load this topic into my head.

**Comment by DmitryOlshansky** [comment]
Sadly have no idea about this part of druntime. Everything sans the first commit is simple and makes sense. The bulk of changes for copy relocations better be reviewed by somebody competent.

**Comment by DmitryOlshansky** [comment]
Auto-merge toggled on

**Comment by DmitryOlshansky** [comment]
It's been hanging for a while here and on trello so I guess nobody can be bothered to double check it

**Pull request merged**
