### PR TITLE
More white space fixes

### PR DESCRIPTION
**Pull request by rainers**
- remove tabs and trailing white space
- add missing files to MANIFEST
- don't rely on MANIFEST for the white space test

### CODE REVIEW

**Comment by rainers** [comment]
The test failure is caused by a bad unittest in std.random that is bound to fail with some probability.

**Comment by yebblies** [comment]
> The test failure is caused by a bad unittest in std.random that is bound to fail with some probability.

You can trigger a re-run of the failing test by going onto the [run's page](https://auto-tester.puremagic.com/show-run.ghtml?projectid=1&runid=1655387&isPull=true) and clicking the 'deprecate' link.

**Comment by rainers** [comment]
> You can trigger a re-run of the failing test by going onto the run's page and clicking the 'deprecate' link.

Thanks, that helped.

**Comment by WalterBright** [comment]
@rainers All test suite heisenbugs should be submitted to bugzilla so they get fixed.

**Comment by rainers** [comment]
> @rainers All test suite heisenbugs should be submitted to bugzilla so they get fixed.

It is already reported: https://issues.dlang.org/show_bug.cgi?id=13853

**Comment by WalterBright** [comment]
@rainers thank you!

**Comment by DmitryOlshansky** [comment]
LGTM

**Comment by 9rnsr** [comment]
Auto-merge toggled on

**Comment by 9rnsr** [comment]
Seems no one has complaint with this PR.

**Pull request merged**
