### PR TITLE
DIP25: implement in druntime

### PR DESCRIPTION
**Pull request by WalterBright**
Replaces https://github.com/D-Programming-Language/druntime/pull/1135

### CODE REVIEW

**Comment by Orvid** [comment]
I object very strongly to this change, because it means that in order for *anyone* to be able to build *any* D code, (unless the -dip25 switch simply enables the checking, and the compiler still allows the return attribute without the switch), they would have to pass the -dip25 switch. I think this would be better implemented as a `version(DIP_25)` rather than forcing it on everything.

**Comment by WalterBright** [comment]
That is not correct. -dip25 is designed to only check the module being compiled, not what is imported. If this ever passes the test suite, you'll see this in action, as only druntime will be compiled with -dip25.

**Comment by andralex** [comment]
that's a really nice pattern we should apply everywhere going forward

**Comment by WalterBright** [comment]
I.e. -dip25 is not designed to be 'viral'

**Comment by Orvid** [comment]
Alright, I have no problem with it in that case.

**Pull request merged**
