### PR TITLE
fixup broken windows build (#1404)

### PR DESCRIPTION
**Pull request by MartinNowak**

### CODE REVIEW

**Comment by andralex** [comment]
Should I merge regardless of the autotester?

**Comment by braddr** [comment]
@andralex never, unless you want the problem to leak to every build, not just this one.  Anyway, I've worked around the problem on the auto-tester.  New build is in-flight.

**Comment by andralex** [comment]
ok thx!

**Comment by andralex** [comment]
Auto-merge toggled on

**Comment by MartinNowak** [comment]
Thx, and sorry for the trouble.

**Pull request merged**
