### PR TITLE
Dwarf EH: add class Object.__cpp_type_info

### PR DESCRIPTION
**Pull request by WalterBright**
See discussion https://github.com/D-Programming-Language/dmd/pull/5342 and http://www.digitalmars.com/d/archives/digitalmars/D/Catching_C_Exceptions_in_D_277799.html#N277849

### CODE REVIEW

**Comment by ibuclaw** [comment]
I think my personal preference would be to have someone get this working on GDC or LDC too, then we can compare notes on how we did it / the best approach.

**Comment by andralex** [comment]
Auto-merge toggled on

**Comment by andralex** [comment]
@ibuclaw guess this PR shouldn't be too contentious.

**Comment by ibuclaw** [comment]
> @ibuclaw guess this PR shouldn't be too contentious 

That depends on whether it's strictly necessary.  I still think that I can make it work without

**Pull request merged**
