### PR TITLE
DIP25: implement in druntime

### PR DESCRIPTION
**Pull request by WalterBright**

### CODE REVIEW

**Comment by CyberShadow** [comment]
No win64.mak change?

**Comment by WalterBright** [comment]
Sorry, forgot it. Will fix.

**Comment by andralex** [comment]
Oops looks like it was failing unittests. Reverting.

**Comment by CyberShadow** [comment]
auto merge auto merge auto merge

**Comment by 9rnsr** [comment]
I'm really not sure why the EXPERIMENTAL feature needs the druntime fix? Any compiler changes for DIP25 should not introduce any library changes. Am I misunderstanding?

**Comment by schveiguy** [comment]
> auto merge auto merge auto merge

Note, auto-merge is not a very well-documented feature... I only figured it out by seeing it happen and guessing.

**Comment by yebblies** [comment]
> Note, auto-merge is not a very well-documented feature... I only figured it out by seeing it happen and guessing.

Do you really think Andrei doesn't know how to use auto-merge?

**Pull request merged**
