### PR TITLE
workaround Issue 2396 - O(N^2) backend optimizations

### PR DESCRIPTION
**Pull request by MartinNowak**

### CODE REVIEW

**Comment by rainers** [comment]
When adding similar workarounds to phobos the discussion in the PR resulted in that it's best to add comments why this workaround is used, so I added `// avoid slow optimizations for large functions @@@BUG@@@ 2396`.

**Comment by WalterBright** [comment]
Missing link: https://issues.dlang.org/show_bug.cgi?id=2396

**Comment by WalterBright** [comment]
Generally, when posting a PR that addresses a bugzilla issue, please provide a link here to the bugzilla issue, and a link in the bugzilla issue pointing back here. Otherwise, nobody reading bugzilla will know there's a patch for it.

**Comment by MartinNowak** [comment]
Done

**Comment by schveiguy** [comment]
LGTM

**Comment by schveiguy** [comment]
Auto-merge toggled on

**Pull request merged**
