### PR TITLE
Add better array extending function

### PR DESCRIPTION
**Pull request by denis-sh**
An attempt to create a function to use in `std.array.appender` and anticipated (let's correct: needed in most cases IMO) "real appender" from [Issue 11138](http://d.puremagic.com/issues/show_bug.cgi?id=11138).

I'm not good in D internals but what happens now in `std.array.appender` looks like a total mess as it attempts to create D array but doesn't respect any hidden info at all.

-

Accidentally it is requested in [Issue 9313 - Provide dynamic array-dedicated "extend" function](https://d.puremagic.com/issues/show_bug.cgi?id=9313).

### CODE REVIEW

**Comment by andralex** [comment]
ping - rebase and mind failures?

**Comment by MartinNowak** [comment]
> It will take some time for me to wrap my head around this so it won't happen too soon.

Last time I thought about this (~1 year ago) I couldn't come up with a single use-case where I require a certain amount of memory but actually want more in order to do something more efficient.
We already provide `.capacity` to query additional memory, so I don't think this is particularly useful.

**Comment by denis-sh** [comment]
> Last time I thought about this (~1 year ago) I couldn't come up with a single use-case where I require a certain amount of memory but actually want more in order to do something more efficient.

Interesting. This pull is just a practical requirement for array builder.

**Comment by MartinNowak** [comment]
> Interesting. This pull is just a practical requirement for array builder.

You mean appender? How is that? Appender already knows the how much memory was actually allocated and can reuse that until it needs to realloc.

**Comment by denis-sh** [comment]
> You mean appender?

`Appender` and its future replacement `Builder` I planed to add that time.

> How is that? Appender already knows the how much memory was actually allocated and can reuse that until it needs to realloc.

When we are out of capacity, we need to grow. And to grow we need a function which accepts how much memory we do *require* and how much memory we just *want* to be allocated to decrease future allocations count.

As we currently lack such function in *druntime* this pull was created.

**Comment by MartinNowak** [comment]
> And to grow we need a function which accepts how much memory we do require and how much memory we just want to be allocated to decrease future allocations count.

There are two schemes that work equally well.
Allocate as much as you require and use the excess you got or
allocate as much as you want and fail if that doesn't work.
The additional sophistication is really unnecessary and creates new problems because now the grow strategy needs to be tuned to the allocation size classes of the GC.

**Comment by DmitryOlshansky** [comment]
> The additional sophistication is really unnecessary and creates new problems because now the grow strategy needs to be tuned to the allocation size classes of the GC.

Looks like it's not appreciated and was there for 2 years.Closing

**Pull request closed without merging**
