### PR TITLE
purge 2.068.1 changelog

### PR DESCRIPTION
**Pull request by MartinNowak**

### CODE REVIEW

**Comment by MartinNowak** [comment]
see https://github.com/D-Programming-Language/dlang.org/pull/1091

**Comment by MartinNowak** [comment]
@CyberShadow you're DAutoTest doesn't rerun when I reopen a PR from the same branch.

**Comment by CyberShadow** [comment]
> when I reopen a PR from the same branch.

Could you elaborate?

**Comment by CyberShadow** [comment]
Whatever you meant, I think what actually happened was that GitHub was caching the PR test status before DAutoTest got to re-update it.

**Comment by MartinNowak** [comment]
> Whatever you meant, I think what actually happened was that GitHub was caching the PR test status before DAutoTest got to re-update it.

Yes, or maybe it was a hickup in the PR callback.

**Comment by MartinNowak** [comment]
Please merge ASAP so I can build the release.

**Comment by CyberShadow** [comment]
How did these changelog entries even end up in the stable branch?

**Comment by CyberShadow** [comment]
Maybe I just don't understand how `changelog.dd` works in Phobos/Druntime

**Comment by MartinNowak** [comment]
> How did these changelog entries even end up in the stable branch?

We commited them with the PR that added this change https://github.com/D-Programming-Language/druntime/pull/1359.

**Pull request merged**
