### PR TITLE
build documentation for core.stdc modules

### PR DESCRIPTION
**Pull request by MartinNowak**
- see #1091

### CODE REVIEW

**Comment by MartinNowak** [comment]
Maybe this encourages someone to bring gmake.exe to our windows builds.
Shouldn't be too hard [Make for Windows](http://gnuwin32.sourceforge.net/packages/make.htm).

**Comment by schveiguy** [comment]
Looks good.

**Comment by schveiguy** [comment]
Auto-merge toggled on

**Comment by schveiguy** [comment]
Who builds the docs online so we can see what this will look like?

**Comment by MartinNowak** [comment]
https://dlang.dawg.eu/phobos-prerelease/core_stdc_complex.html

**Comment by schveiguy** [comment]
Ugh, something definitely isn't right with how I did it :)

screen shot 2015-02-17 at 2 09 46 pm

The html doesn't look right at all. I'll see if it's something I can fix.

**Comment by MartinNowak** [comment]
thx

**Comment by schveiguy** [comment]
OK, so here is the problem, the link to the c header file looks like this:

```
pubs.opengroup.org/onlinepubs/009695399/basedefs/complex.h.html
```

Ddoc sees that term `complex` and says "oooh! that's a keyword, I want to emphasize it properly!" and proceeds to insert an anchor around that part of the URL, including quotes and extra shit that totally screw up the real link. How does one say "do not do any parsing of this text"? I can't use the underscore trick (I don't think) because the entire link is passed as one parameter to the C_HEADER_DESCRIPTION macro. There has to be a way to do this...

**Comment by schveiguy** [comment]
Sorry, it's not because it's a keyword it's because complex is a module/symbol.

**Comment by schveiguy** [comment]
OK, I guess I have to fix it by putting the underscore in each .d file.

**Comment by MartinNowak** [comment]
I faintly remember that I tried this and came out with a similar conclusion.
But I didn't remember the underscore trick.

**Comment by schveiguy** [comment]
Hah, it's actually already used right next to it: https://github.com/D-Programming-Language/druntime/blob/master/src/core/stdc/complex.d#L11

I'll set about making this PR. As a good sidenote, I figured out how to build the library docs, so now I can at least test before submitting ;)

Annoying that you can't say "don't change this text at all" some way, that doesn't require you to underscore each "symbol".

**Comment by MartinNowak** [comment]
> I'll set about making this PR. As a good sidenote, I figured out how to build the library docs, so now I can at least test before submitting ;)

Did you build the docs of druntime or did you use dlang.org?
Anyhow that's good news. It would be even better, if the auto-tester build the docs for you so that everybody gets more involved in writing good docs.

> Annoying that you can't say "don't change this text at all" some way, that doesn't require you to underscore each "symbol".

ddoc feature requests > @andralex

**Comment by schveiguy** [comment]
PR submitted: #1177

**Comment by schveiguy** [comment]
> Did you build the docs of druntime or did you use dlang.org?

I used dlang.org. I tried using druntime to build the docs, but it does not do any CSS or macros from dlang.org (annoyingly, the macro is defined in dlang.org, so that blurb completely goes away).

I ran the commands:

```
make -f posix.mak html
make -f posix.mak druntime-prerelease
```

**Pull request merged**
