### PR TITLE
fix definition of hasDWCAS in PR1100

### PR DESCRIPTION
**Pull request by rainers**
see comments in https://github.com/D-Programming-Language/druntime/pull/1100

### CODE REVIEW

**Comment by MartinNowak** [comment]
Auto-merge toggled on

**Comment by MartinNowak** [comment]
thx

**Comment by MartinNowak** [comment]
Auto-merge toggled off

**Comment by andralex** [comment]
@MartinNowak why off?

**Comment by MartinNowak** [comment]
It's fine, was just wondering if something else was wrong.
https://github.com/D-Programming-Language/druntime/pull/1100#issuecomment-74290536

**Comment by MartinNowak** [comment]
Auto-merge toggled on

**Pull request merged**
