### PR TITLE
allocating a pool must be done in the if (disabled) block

### PR DESCRIPTION
**Pull request by MartinNowak**
- or the else branch gets executed on a successful pool allocation

### CODE REVIEW

**Comment by MartinNowak** [comment]
fixup for #1081

**Comment by rainers** [comment]
Ooops, should have reviewed more carefully.

I was about to pick on `if (!tryAlloc() && (!newPool(1, false) || !tryAlloc()))` in #1081 which might cause similar issues. IMO it is too terse to be readable well. Lines like this also make debugging, coverage analysis or profiling more difficult (similar to statements on the same line as `ìf`).

**Comment by rainers** [comment]
Auto-merge toggled on

**Comment by MartinNowak** [comment]
> That would be an improvement but I was rather thinking of converting to separate if statements.

I find the nested version even harder to understand and I generally have problems following nested if-else flows.

```d
if (!tryAlloc() && !tryAllocNewPool())
    onOutOfMemoryError();
```
```d
if (!tryAlloc())
{
    if (!tryAllocNewPool())
        onOutOfMemoryError();
}
```

**Pull request merged**
