### PR TITLE
use foreach to decode in rt/adi.d

### PR DESCRIPTION
**Pull request by WalterBright**
Use D core features.

### CODE REVIEW

**Comment by schveiguy** [comment]
In my previous tests of foreach vs. hand-written or calling decode, foreach was a lot slower because it used non-inlined code. Has that changed?

**Comment by andralex** [comment]
Whichever the case, it's good to dogfood this way because we create pressure for better implementation.

**Comment by andralex** [comment]
Auto-merge toggled on

**Comment by WalterBright** [comment]
I agree. Removing the workarounds is the first step to improving things. foreach over strings needs to be replaced with a range-based implementation.

**Comment by WalterBright** [comment]
See also https://github.com/D-Programming-Language/druntime/pull/1237 for a similar change.

**Comment by schveiguy** [comment]
Wait, this is in druntime. Why is calling druntime more dogfooding than calling druntime? There's also no way autodecoding or encoding string ranges are getting in here, is there?

**Comment by schveiguy** [comment]
Auto-merge toggled off

**Comment by schveiguy** [comment]
Re-toggle if you disagree, I just don't think it's the right move here. If it were Phobos, that's different.

**Comment by andralex** [comment]
foreach with autodecoding has been in D for a long time

**Comment by andralex** [comment]
Auto-merge toggled on

**Comment by schveiguy** [comment]
Sure, the argument was "it should be done with auto-decoding ranges anyway" which probably aren't coming to druntime. So that's what I was responding to.

None of the arguments here make much sense, but this entire file seems riddled with inefficiencies and dangerous code (sorting an array of code points?), so I'm not going to argue any more about it.

**Comment by WalterBright** [comment]
> the argument was "it should be done with auto-decoding ranges anyway" which probably aren't coming to druntime.

But they are!

**Pull request merged**
