### PR TITLE
core.sys.windows.stat: Fix constness

### PR DESCRIPTION
**Pull request by CyberShadow**

### CODE REVIEW

**Comment by DmitryOlshansky** [comment]
LGTM

**Comment by DmitryOlshansky** [comment]
Auto-merge toggled on

**Comment by schveiguy** [comment]
Auto-merge toggled off

**Comment by schveiguy** [comment]
Re-enable auto merge after the fix for the win64 build.

**Comment by CyberShadow** [comment]
I don't think I can do anything about "Fatal Error: Out of memory".

**Comment by schveiguy** [comment]
@CyberShadow I think it will be fixed via https://github.com/D-Programming-Language/phobos/pull/4173. If that passes, then we can re-enable.

**Comment by CyberShadow** [comment]
OK.

Though I don't understand the point of explicitly disabling and then enabling it.

**Comment by schveiguy** [comment]
@CyberShadow I want priority given to that PR. The win64 machine takes an hour to complete it's tests.

**Comment by CyberShadow** [comment]
Sure, but does auto-merge affect priority?

**Comment by yebblies** [comment]
Yes.  Branch builds, then auto-merge pulls, then the rest of the pulls, each set sorted by time of last commit.

**Comment by CyberShadow** [comment]
OK, thanks.

**Comment by schveiguy** [comment]
Auto-merge toggled on

**Comment by braddr** [comment]
You've got the first two backwards:  1) auto merge pulls, 2) branch, 3) rest of pulls

**Pull request merged**
