### PR TITLE
explicitly disable using a conf file during the build

### PR DESCRIPTION
**Pull request by braddr**

### CODE REVIEW

**Comment by MartinNowak** [comment]
Auto-merge toggled on

**Comment by MartinNowak** [comment]
This is still nonsensical IMO.
We're adding `-conf=` switches to every project because someone __might__ have a conf in it's home dir, not because we want to configure the compiler.
That couldn't even be done, if you'd actually need a working dmd.conf. We're stuck with something similar here https://github.com/D-Programming-Language/dlang.org/pull/758.
Please reconsider changing the conf precedence.

**Comment by MartinNowak** [comment]
@rainers says this breaks building on Windows for him.
Looks like we should revert this.
https://github.com/D-Programming-Language/druntime/pull/1147#issuecomment-74469343

**Comment by rainers** [comment]
Not sure we have to revert it completely, making it optional by defining `CONF=-conf=` and then use `$(CONF)` could help. Defaulting to an empty setting would avoid breaking any build script, but still allow the build server to work without configuration file.

**Pull request merged**
