### PR TITLE
Treat division by 0 as an error in Duration and consolidate code.

### PR DESCRIPTION
**Pull request by jmdavis**
Duration should never have checked for division by 0 and thrown a
TimeException when it occurred. The OS/hardware already checks for that,
and it should be considered a logic error. Checking for it and possibly
throwing just slows the code down and makes it so that it can't be @nogc.

This is technically a breaking change, but it will only break code which
doesn't bother to avoid dividing by 0 and then catches TimeException
when it occurs, and such code is likely extremely rare, if it exists at
all. Given the fact that the odds of actually breaking code are
extremely low and that this allows us to make Duration fully @nogc except
for toString, I think that it's worth the risk.

### CODE REVIEW

**Comment by DmitryOlshansky** [comment]
LGTM and nice code consolidation btw

**Comment by MartinNowak** [comment]
Auto-merge toggled on

**Comment by denis-sh** [comment]
IMHO breaking change pull should have a link to a corresponding changelog pull.

**Comment by schveiguy** [comment]
> IMHO breaking change pull should have a link to a corresponding changelog pull.

I agree, but to that end, I believe we now have individual changelog files for each sub-project. We should stop accepting pulls without a changelog entry when one is warranted.

**Comment by jmdavis** [comment]
Enhancement request created and marked as FIXED so that this will show up in the changelog: https://issues.dlang.org/show_bug.cgi?id=15221

**Pull request merged**
