### PR TITLE
detab, tolf, remove trailing whitespace

### PR DESCRIPTION
**Pull request by rainers**
Trying not to commit bad line endings again, I added checkwhitespace to my build batch. This fails for some existing files, though.

### CODE REVIEW

**Comment by andralex** [comment]
This is bound to happen again. Do you think you could investigate adding commit hooks to enforce this stuff? Otherwise we'll be spending time again and again pulling PRs like this.

**Comment by rainers** [comment]
A commit hook needs every contributor to setup his environment which will be different on every platform and tooling. I think the simpler and better approach is to run the check on the auto tester very much like it is done for the dmd sources now.

If we can make the checkwhitespace tool available for druntime/phobos aswell, we could add similar targets to the respective makefiles.

**Comment by joakim-noah** [comment]
I think that's what Andrei meant by a "commit hook," to have the check run automatically on the auto-tester when the PR is submitted.  Either way, I agree with you that that is the best approach, failing or amending the PR quickly if it doesn't meet certain criteria.

**Comment by DmitryOlshansky** [comment]
@braddr @CyberShadow - any thoughts on running detab, tolf etc. to detect bad whitespace in auto-tester?

**Comment by CyberShadow** [comment]
Well, all you need to do to make Brad's tester test something is add it to the makefile. I could also add it to mine, in theory, I suppose.

**Comment by rainers** [comment]
I think it needs checkwhitespace from the dmd folder to be precompiled and accessible somewhere on the build server. Then we could add a check to the auto-tester target in posix.mak for druntime and phobos. For druntime I used this:
```
_TOCHECK = $(MANIFEST)
TOCHECK = $(filter-out mak\COPY mak\DOCS mak\IMPORTS mak\SRCS mak\MANIFEST,$(_TOCHECK))

checkwhitespace:
	../tools/checkwhitespace $(TOCHECK)
```

**Comment by DmitryOlshansky** [comment]
@rainers that or conjure something with shell scripts. `grep -P "^.* +$` would work for tailing white space check, `grep -P "\r\n|\t"` for windows line endings and tabs.

**Comment by rainers** [comment]
I've rebased this and tried a makefile rule to be run by the auto tester, but I could not really test it, because grep does some strange things with CR, even with -U. -P also wasn't available with the version I used.

Using grep is probably better than checkwhitespace from the dmd folder because it will give you an idea where the error is.

**Comment by DmitryOlshansky** [comment]
LGTM

**Comment by DmitryOlshansky** [comment]
Auto-merge toggled on

**Comment by yebblies** [comment]
> Using grep is probably better than checkwhitespace from the dmd folder because it will give you an idea where the error is.

That isn't super important because once you know there's a whitespace problem somewhere in a file you can just search for it in your editor.

**Comment by rainers** [comment]
I've added some improvements here: https://github.com/D-Programming-Language/druntime/pull/1315
https://github.com/D-Programming-Language/phobos/pull/3474 adds a similar check to phobos.

**Comment by rainers** [comment]
> That isn't super important because once you know there's a whitespace problem somewhere in a file you can just search for it in your editor.

True, though it is a small inconvenience. There are some other downsides to the approach in dmd though:
- building checkwhitespace every time adds a noticeable delay during a build
- if an invalid UTF8 character creeps in, checkwhitespace just bails out without indication in what file it is in.
- it cannot be used for the files in the mak folder because the makefile detection does not work there.

The grep version has some disadvantages, too:
- it doesn't detect invalid UTF8 charcters
- it doesn't tell you what the actual problem is on the displayed line: CR, tab or trailing whitespace?

**Comment by yebblies** [comment]
> The grep version has some disadvantages, too:

**Comment by rainers** [comment]
> Also doesn't work on windows.

It's a bit more complicated to setup (it needs a unix-make and a "recent" grep, later than 2005), but you can use druntime\posix.mak for the check on windows, too. See #1315.

**Comment by yebblies** [comment]
The spurious druntime failures refer to grep, is the whitespace check possibly involved in a race condition?  Does it depend on any generated files?

**Comment by rainers** [comment]
> Does it depend on any generated files?

No, it just checks files in the MANIFEST variable.

**Comment by schveiguy** [comment]
Just FYI, the spurious failures should get fixed here: https://github.com/D-Programming-Language/druntime/pull/1390

The grep is failing because of a race condition, and some copy paste issues.

**Pull request merged**
