### PR TITLE
dev/android-linux-version-conflation

### PR DESCRIPTION
**Pull request by mathstuf**
Base of #764 to hoist `Android` blocks above `linux` blocks. Also removes arch-specific blocks where possible.

### CODE REVIEW

**Comment by andralex** [comment]
What's the status of this?

**Comment by mathstuf** [comment]
@joakim-noah what is the status of glibc split? I'll try to make some time for this (and the other branch which needs to be split) on the weekend, but no guarantees.

**Comment by joakim-noah** [comment]
It's been waiting for review for awhile now, #1010, Martin said he'd get to it soon and has commented previously that the approach looks good.  So there's no need for this PR but the rest of your larger #764 is worth getting merged.  I'll be happy to review that if you split it up.

**Comment by DmitryOlshansky** [comment]
@joakim-noah good to close this?

**Comment by joakim-noah** [comment]
Yes, since #1010 was finally merged a couple months ago, this pull is obsolete.  The first commit, where he removes arch blocks, had similar functionality merged in #1267.  I haven't checked to see if he has anything in his first commit that I missed, but he can always compare those two and submit later if necessary.

**Pull request closed without merging**
