### PR TITLE
Add errno constants for Linux: AArch64, MIPS64, PPC64, SystemZ

### PR DESCRIPTION
**Pull request by redstar**

### CODE REVIEW

**Comment by ibuclaw** [comment]
Look good.  Though I have today keep reminding myself what systemz is.

**Comment by ibuclaw** [comment]
Auto-merge toggled on

**Comment by redstar** [comment]
Would "Big Iron" be a better name? ;-)

**Comment by ibuclaw** [comment]
> Would "Big Iron" be a better name? ;-)

Oh, so I can use it to press shirts and trousers?  :-P

**Pull request merged**
