### PR TITLE
issue 14327: move call to init_msvc() into rt_init()

### PR DESCRIPTION
**Pull request by rainers**
https://issues.dlang.org/show_bug.cgi?id=14327

stdin,stdout,stderr handles are only initialized when running d_run_main, but not rt_init.

### CODE REVIEW

**Comment by rainers** [comment]
Not sure if this should be against stable instead. It's not a regression, though we now support a new platform (win32/mscoff) that doesn't work in this use case.

**Comment by slimshader** [comment]
To clarify: I originally reported this issue for x64 app. Now I also tested mscoff32 version to see if things were resolved in 2.069

**Comment by ZombineDev** [comment]
@rainers It's better to target stable, so that it can get more real world testing and what is maybe more important - so we can have better out-of-the-box experience on Windows sooner rather than later, something many have been asking for.

**Comment by MartinNowak** [comment]
I picked it over to stable de2788d911129545531e0e42d1c8630b3f406e7c.

**Comment by rainers** [comment]
> I picked it over to stable de2788d.

Thanks.

> To close the bugzilla ticket you should use fix Issue 14327, then it will also show up in the changelog.

I wasn't sure it completely fixes the issue, because there is also the trouble with linker errors without D main. Rereading the bug report now, that's not exactly in the bug itself, but in a comment.

**Pull request merged**
