### PR TITLE
Fix epoll_event alignment (issue 14702)

### PR DESCRIPTION
**Pull request by tomerfiliba**

### CODE REVIEW

**Comment by JinShil** [comment]
Link to issue for convenience:  https://issues.dlang.org/show_bug.cgi?id=14702

**Comment by DmitryOlshansky** [comment]
LGTM

**Comment by burner** [comment]
please rebase to head

**Comment by tomerfiliba** [comment]
rebased

**Comment by burner** [comment]
LGTM

**Comment by DmitryOlshansky** [comment]
Auto-merge toggled on

**Pull request merged**
