### PR TITLE
fix Issue 14157

### PR DESCRIPTION
**Pull request by 9il**
https://issues.dlang.org/show_bug.cgi?id=14157

### CODE REVIEW

**Comment by yebblies** [comment]
Won't this lead to horrific loss of precision?

**Comment by 9il** [comment]
For 80 bit `reals` it can, but `std.math` can be used. 
Hmm, I will add support for real into `fsum`.

Have you an idea how to fix loss of precision in `core.stdc` for MS CRuntime?

**Comment by schveiguy** [comment]
fabs is available for long double with C++ binding. See:

https://msdn.microsoft.com/en-us/library/18z15bk0.aspx

We should be able to fix this by extern(C++), no?

**Comment by 9il** [comment]
Thanks!
I have removed declarations from `core.stdc.math` and added them to `core.stdc.tgmath`  https://github.com/D-Programming-Language/druntime/pull/1163
This PR provide the same behaviour like C/C++ does.

**Comment by yebblies** [comment]
> fabs is available for long double with C++ binding. See:

But msvc long double is just double.

**Comment by 9il** [comment]
@yebblies So this PR is correct?

**Comment by schveiguy** [comment]
Yeah, @yebblies is right. Ironically, 16-bit windows treated `long double` as 80 bit, but that was removed as of Win32: https://msdn.microsoft.com/en-us/library/9cx8xs15.aspx

There are two choices then (three if you count @klickverbot's, but I don't think requiring yet another non-standard runtime is a good idea, especially for something as obscure as this):

1. Remove `fabs(real)` overload for windows. This will make it a compiler error instead of linker error.
2. Merge this PR, masking the fact that your 80 bit reals will get truncated.

I'd say we should opt for 1, and people who care about windows support will at least be aware that their data is being truncated (i.e. they have to perform the cast themselves). I don't think core.stdc should be in the business of manipulating data for the purpose of calling C functions, we should just have as direct bindings as possible.

**Comment by 9il** [comment]
@schveiguy 
I remove the overload in #1163. But any way the overload should be defined in `core.stdc.tgmath` like in #1163. If you think we should remove overload why you have closed it?

**Comment by schveiguy** [comment]
I didn't think about re-purposing #1163 to do this, sure, reopen if you want.

**Comment by 9il** [comment]
I have not permission to do it ;(

**Comment by schveiguy** [comment]
> I have not permission to do it ;(

Oh, really? I didn't know that (that's kind of a dumb feature, you can just open a new pull request)! I'll reopen it.

**Pull request merged**
