### PR TITLE
add Visual D parser benchmark

### PR DESCRIPTION
**Pull request by rainers**
This adds the parser and semantic engine that used to power Visual D as a benchmark. It was used as a benchmark for the precise GC presented at DConf2013. It is deprecated by Visual D and replaced by DParser also used by Mono-D, so it is not up-to-date with current dmd, and not changed a lot anymore (apart from being kept compiling).

It currently tests parsing std.datetime. Maybe it is better to use the parser sources itself to avoid changing results due to std.datetime evolving.

It uses tabs for indentation. Should it be converted to spaces? That would make it even larger...

### CODE REVIEW

**Comment by MartinNowak** [comment]
So VisualD now uses that one? https://github.com/aBothe/D_Parser

**Comment by MartinNowak** [comment]
> It uses tabs for indentation. Should it be converted to spaces? That would make it even larger...

There is no history anyhow, so indeed I'd be in favor of detabbing everything.

**Comment by MartinNowak** [comment]
> Maybe it is better to use the parser sources itself to avoid changing results due to std.datetime evolving.

Yeah, parsing vdparse itself makes more sense IMO.

**Comment by MartinNowak** [comment]
see https://github.com/rainers/druntime/pull/3

**Comment by rainers** [comment]
> So VisualD now uses that one? https://github.com/aBothe/D_Parser

Yes, it's used as an alternative engine since about 2 years.

**Pull request merged**
