### PR TITLE
reduce excessive unittests and template bloat

### PR DESCRIPTION
**Pull request by MartinNowak**
- move enum name and index function out of them template
- check const conversions once, instead of repeating
  this for every operation
- using a const value guarantees that the method can be
  called for mutable and immutable values as well
- 15% compile time and 10% binary size of unittest library

### CODE REVIEW

**Comment by MartinNowak** [comment]
I stumbled over this while trying to bisect dmd compile time increases.

**Comment by schveiguy** [comment]
See #1278, these will probably conflict. I'd recommend pulling that one first.

**Comment by DmitryOlshansky** [comment]
#1278 is in - time to rebase?

**Comment by MartinNowak** [comment]
updated

**Comment by 9rnsr** [comment]
Auto-merge toggled on

**Pull request merged**
