### PR TITLE
16-Byte Cas, AtomicStore and AtomicLoad added to core.atomic.

### PR DESCRIPTION
**Pull request by adamsaka**
16-Byte operations added for atomicStore, atomicLoad and CAS (module: core.atomic).
(ie. double-word added for 64 bit machines.  It is already available on 32 bit machines.)

### CODE REVIEW

**Comment by MartinNowak** [comment]
Can you please add a unittest below here https://github.com/adamsaka/druntime/blob/e030035e67ee7a53063e31416e9568855a6b6eb6/src/core/atomic.d#L1235.

**Comment by braddr** [comment]
This is nearly a dup of druntime pull #961

**Comment by adamsaka** [comment]
Added a simple unittest.  

Sorry I didn't see the other pull request.  I just had this function in my own code, and thought it would be better as part of the runtime.  Feel free to use which ever version is better.

**Comment by MartinNowak** [comment]
And now it has the same Win64 failure as the other pull :o.
Any clue?

**Comment by adamsaka** [comment]
Yep, I thinks so. The data needs to be 16 byte aligned for that instruction.  I will need to ensure the unit test data is aligned.  (Sorry that was a bit sloppy).  I will add an assertion to warn potential users also.  Will update when I get home.

Reading the other push comments, do you think I should add compile time checks to ensure the compiling CPU supports the instruction?  Won't help much with binary releases, but should help users debug.  It would probably slow things down too much to perform this check at runtime.  Could probably add a check for legacy 32 bit machines also.

**Comment by MartinNowak** [comment]
> Reading the other push comments, do you think I should add compile time checks to ensure the compiling CPU supports the instruction? Won't help much with binary releases, but should help users debug. It would probably slow things down too much to perform this check at runtime.

Use an assertion, that won't affect release builds.

> Could probably add a check for legacy 32 bit machines also.

A check for 8b cas? Sure.

**Comment by adamsaka** [comment]
I did some trial and error checking on Win64 and it appears that the calling convention is the problem.  Unfortunatly it's not documented with the rest of the D ABI.  It seems DMD uses the standard windows 64 convention but reverses the order of the parameters.  

The windows documentation states the parameters are passed to the RCX, RDX, R8, R9 registers in that order.  CAS was getting the parameters as R8, RDX, RCX.   This may be a bug?  I have created a Win64 version of the code.  I wrote it in a way that should work even if someone changes this register ordering to the standard windows ordering.

I've tested a simple version of the CAS function on Win64, but I don't have a full Win64 environment setup that can build the runtime.  (If it passes the tests now, hopefully I won't need to).

16 byte alignment added to the unit test.

I will add the instruction supported checks tomorrow.  (Can be a different push if you prefer)

**Comment by MartinNowak** [comment]
Yes, extern(D) arguments are pushed in reverse order, forgot why.

**Comment by MartinNowak** [comment]
Auto-merge toggled on

**Comment by MartinNowak** [comment]
Thanks

**Comment by andralex** [comment]
Thanks for this work! I'll close 961.

**Comment by denis-sh** [comment]
Nitpicks: this pull added few lines with just spaces and curly braces not on its own line.
Also changes like e030035 should be amended in the parent commit to not pollute the history.

**Pull request merged**
